Inputs:
    
    
Labels:

    
KerasModel: three_layer_model
KerasModelRetrain: three_layer_model_constraint
KerasLoss: categorical_crossentropy
L1Reg: 0.0001
NormalizeInputs: 1 
InputType: Dense
Seed: 42